---
output: 
  md_document:
    variant: gfm
---

# A framework for capturing indirect impacts in site-level screening for biodiversity risks
Divya Narain^a^, Jacob Bedford^b^, Elspeth Grace^b^, Alfred Muge^b^, Aime Rankin^b^, Matt Jones^b^, Sebastian Dunnett^b^

^a^Smith School of Enterprise and the Environment, University of Oxford

^b^UN Environment Programme World Conservation Monitoring Centre, Cambridge, UK

>Site-based industrial operations such as mining, oil and gas extraction, and renewable energy development are associated with many direct and indirect impacts on biodiversity. Consideration of the full range of these impacts when selecting a buffer distance to approximate Area of Influence (AoI) of a project is critical for effective biodiversity risk screening. Indirect impacts, however, are elusive despite often being more extensive than direct ones, both temporally and spatially. There is also limited clarity on the distinction between direct and indirect impacts, leading to the latter either being missed from screening analyses, or misclassified as direct impacts. Here we propose a definition of indirect impacts and a framework for incorporating them in risk and impact analyses. We define indirect impacts as those that are triggered by wider socio-economic and demographic changes induced by the project and not directly by project operations. Indirect impacts manifest through three pathways: increased access to intact ecosystems, increased in-migration and settlement, and increased viability of other economic activity. A range of factors, however, can act as predictors of the likelihood and intensity of indirect impacts and form the basis of a decision-making framework to select a buffer that captures their AoI effectively.

This repository contains supporting code for a manuscript accepted for publication at *Methods in Ecology and Evolution*. A link to this paper will be added when published.

The processing script, *aoi_decision_layer.R* takes six data inputs to produce a raster screening layer that supports the assessment of project indirect impacts. To reproduce the analysis, researchers must first acquire the six input datasets from source:

| Dataset                                       | Link                                                                                                                                           | Variant used                                                | Copyright                                      |
|-----------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------|------------------------------------------------|
| Global roadless areas                         | [https://roadless.online/data/](https://roadless.online/data/)                                                                                 | Global shapefile                                            | Open Data Commons Open Database Licence (ODbL) |
| Global Human Settlement Model grid (GHS-SMOD) | [https://human-settlement.emergency.copernicus.eu/download.php?ds=smod](https://human-settlement.emergency.copernicus.eu/download.php?ds=smod) | 1km in Mollweide projection                                 | CC BY                                          |
| Global gridded GDP data                       | [https://zenodo.org/records/16741980](https://zenodo.org/records/16741980)                                                                     | 2020 total GDP at 30arcsecs                                 | CC BY                                          |
| Travel time to cities                         | [https://doi.org/10.6084/m9.figshare.7638134.v4](https://doi.org/10.6084/m9.figshare.7638134.v4)                                               | "travel_time_to_cities_9.tif", i.e. settlements over 50,000 | CC BY                                          |
| Global human modification dataset             | [https://doi.org/10.5281/zenodo.14502572](https://doi.org/10.5281/zenodo.14502572)                                                             | "HMv20240801_2022s_AA_300.tif", i.e. all threats combined   | CC BY                                          |
| Critical Habitat                              | [https://doi.org/10.34892/snwv-a025](https://doi.org/10.34892/snwv-a025)                                                                       | Basic                                                       | CC BY                                          |

The accompanying script, *aoi_plot.R*, allows researchers to recreate figures in the paper.

Output data are on Zenodo [here](https://doi.org/10.5281/zenodo.16997584).